"""UserProduct table

Revision ID: 071706495efc
Revises: 3e03b2ecbe85
Create Date: 2020-04-20 04:39:58.564495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071706495efc'
down_revision = '3e03b2ecbe85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_product')
    # ### end Alembic commands ###
