"""aad housewares table

Revision ID: 32cf9e87668a
Revises: dbb1e8dd014f
Create Date: 2020-04-20 04:32:01.201677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cf9e87668a'
down_revision = 'dbb1e8dd014f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housewares', sa.Column('link', sa.String(length=255), nullable=True))
    op.add_column('housewares', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housewares', 'name')
    op.drop_column('housewares', 'link')
    # ### end Alembic commands ###
