"""housewares table

Revision ID: 37e9fca9f6ef
Revises: 8dcf53b28e06
Create Date: 2020-04-18 09:55:24.149347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e9fca9f6ef'
down_revision = '8dcf53b28e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housewares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('housewares')
    # ### end Alembic commands ###
