"""add all tables

Revision ID: 70571fae337e
Revises: 071706495efc
Create Date: 2020-04-20 06:57:36.011667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70571fae337e'
down_revision = '071706495efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('pc_id', sa.Integer(), nullable=False),
    sa.Column('pc_name', sa.String(length=255), nullable=True),
    sa.Column('ps_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pc_id')
    )
    op.create_table('customer__services',
    sa.Column('services_id', sa.Integer(), nullable=False),
    sa.Column('services', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('services_id')
    )
    op.create_table('disney',
    sa.Column('disney_id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('disney_id')
    )
    op.create_table('merchant',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('shipping_cart_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_create_at'), 'order', ['create_at'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('cary_type', sa.Integer(), nullable=True),
    sa.Column('card_number', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('pets',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('product',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('pname', sa.String(length=255), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('pc_id', sa.Integer(), nullable=True),
    sa.Column('ps_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('shopping_cart',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('status',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('shipment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('subcategory',
    sa.Column('ps_id', sa.Integer(), nullable=False),
    sa.Column('ps_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ps_id')
    )
    op.create_table('voucher',
    sa.Column('v_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('expiary', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('v_id')
    )
    op.add_column('sports_and_travel', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('toys_and_books', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toys_and_books', 'name')
    op.drop_column('sports_and_travel', 'name')
    op.drop_table('voucher')
    op.drop_table('subcategory')
    op.drop_table('status')
    op.drop_table('shopping_cart')
    op.drop_table('product')
    op.drop_table('pets')
    op.drop_table('payment')
    op.drop_index(op.f('ix_order_create_at'), table_name='order')
    op.drop_table('order')
    op.drop_table('merchant')
    op.drop_table('disney')
    op.drop_table('customer__services')
    op.drop_table('category')
    # ### end Alembic commands ###
