"""Add SportsAndTravel table

Revision ID: 713177aa0a82
Revises: 32cf9e87668a
Create Date: 2020-04-20 04:37:02.622786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713177aa0a82'
down_revision = '32cf9e87668a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sports_and_travel', sa.Column('link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sports_and_travel', 'link')
    # ### end Alembic commands ###
