"""SportsAndTravel table

Revision ID: c7d6422e3825
Revises: 37e9fca9f6ef
Create Date: 2020-04-18 09:57:33.524933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d6422e3825'
down_revision = '37e9fca9f6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports_and_travel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sports_and_travel')
    # ### end Alembic commands ###
