"""ToysAndBooks table

Revision ID: dbb1e8dd014f
Revises: c7d6422e3825
Create Date: 2020-04-18 09:59:37.542377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb1e8dd014f'
down_revision = 'c7d6422e3825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys_and_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys_and_books')
    # ### end Alembic commands ###
